<?php

namespace LT\UpvoteBundle\Repository;

/**
 * VoteAggregateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteAggregateRepository extends \Doctrine\ORM\EntityRepository
{
}
